# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false

matrix:
  include:
    - name: "callr 3.2.0"
      r_github_packages: r-lib/callr@v3.2.0
    - name: "callr 3.3.0+ (master)"
      r_github_packages: r-lib/callr
    - name: "my fork"
      r_github_packages: jdblischak/callr
